version: '3'
services:
  db:
    image: postgres:11
    container_name: 'ohs-db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ohs-user
      POSTGRES_DB: ohs
    volumes:
      - ohs_data:/var/lib/postgresql/data

volumes:
  ohs_data:
