version: 2
jobs:
  build-backend:
    docker:
      - image: circleci/python:3.7.2
        environment:
          OHS_DB_HOST: 127.0.0.1
          OHS_DB_NAME: ohs
          OHS_DB_USER: ohs-user
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: ohs-user
          POSTGRES_DB: ohs

    working_directory: ~/ohs

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt install -y postgresql-client || true
            cd backend
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools poetry
            poetry install

      - save_cache:
          paths:
            - ./backend/venv
          key: v1-dependencies-{{ checksum "backend/poetry.lock" }}

      - run:
          name: wait for DB
          command: |
            cd backend
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 \
                && echo Success \
                && psql -h 127.0.0.1 -d ohs -U ohs-user -w -a -f core/table_setup.sql \
                && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: run tests
          command: |
            cd backend
            . venv/bin/activate
            make lint
            make tests

      - run:
          name: upload coverage
          command: |
            cd backend
            . venv/bin/activate
            pip install codecov
            codecov

  build-frontend:
    docker:
      - image: circleci/node:11.10

    working_directory: ~/ohs

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "ohs_gui/package-lock.json" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd ohs_gui
            npm install

      - save_cache:
          paths:
            - ./ohs_gui/node_modules
          key: v1-dependencies-{{ checksum "ohs_gui/package-lock.json" }}

      - run:
          name: run tests
          command: |
            cd ohs_gui
            npm test -- --ci


workflows:
 version: 2
 full-build:
   jobs:
     - build-backend
     - build-frontend

